baseurl = "https://example.com"
languageCode = "ja"
title = "himetani's cafe"
theme = "cactus-plus"
#copyright = "&copy; <a href=\"https://github.com/himetani\">himetani</a> 2016"
hasCJKLanguage = true

[params]
	author = "himetani"
	description = "Have a break?"
	bio = "Have a break?"

	twitter = "himetani_cafe"

	enableDisqus = true
	disqusShortname = "himetani"

	enableSummary = true
	useDescriptionReplaceSummary = false

	# show latest posts in single page
	showLatestPosts = true
	readMore = "Read more"

	# Share
	enableShare = true
	tweet = "Twitter"

	iconFont = "font-awesome"

[social]
	twitter-square = "https://www.twitter.com/himetani_cafe"
	github-square = "https://www.github.com/himetani"
